import os
import json
from datetime import datetime, timedelta
import pytz
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

class DailySummaryTracker:
    def __init__(self):
        self.log_file = 'daily_summary_log.json'
        self.load_data()
    
    def load_data(self):
        try:
            with open(self.log_file, 'r') as f:
                self.data = json.load(f)
        except:
            self.data = {
                'last_summary_date': None,
                'daily_stats': {}
            }
    
    def save_data(self):
        with open(self.log_file, 'w') as f:
            json.dump(self.data, f, indent=2)
    
    def log_run(self, articles_found, timestamp=None):
        if timestamp is None:
            timestamp = datetime.now(pytz.UTC)
        
        date_str = timestamp.strftime('%Y-%m-%d')
        
        if date_str not in self.data['daily_stats']:
            self.data['daily_stats'][date_str] = {
                'runs': 0,
                'total_articles_found': 0,
                'run_times': []
            }
        
        self.data['daily_stats'][date_str]['runs'] += 1
        self.data['daily_stats'][date_str]['total_articles_found'] += articles_found
        self.data['daily_stats'][date_str]['run_times'].append(timestamp.isoformat())
        
        self.save_data()
    
    def get_yesterday_stats(self):
        yesterday = datetime.now(pytz.UTC) - timedelta(days=1)
        yesterday_str = yesterday.strftime('%Y-%m-%d')
        
        return self.data['daily_stats'].get(yesterday_str, {
            'runs': 0,
            'total_articles_found': 0,
            'run_times': []
        })
    
    def send_daily_summary(self):
        yesterday = datetime.now(pytz.UTC) - timedelta(days=1)
        yesterday_str = yesterday.strftime('%Y-%m-%d')
        stats = self.get_yesterday_stats()
        
        # Create summary email
        sender = os.environ.get('LOGISTICS_EMAIL_USER', 'sc.sentinelnews@gmail.com')
        password = os.environ.get('LOGISTICS_EMAIL_PASSWORD', '')
        recipient = os.environ.get('LOGISTICS_EMAIL_RECIPIENT', sender)
        
        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .header {{ background-color: #2c3e50; color: white; padding: 20px; text-align: center; }}
        .stats {{ background-color: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0; }}
        .metric {{ display: inline-block; margin: 10px 20px; text-align: center; }}
        .number {{ font-size: 2em; font-weight: bold; color: #3498db; }}
        .label {{ color: #7f8c8d; }}
        .footer {{ color: #7f8c8d; font-size: 0.9em; margin-top: 30px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚢 Daily Logistics Intelligence Summary</h1>
        <h2>{yesterday_str}</h2>
    </div>
    
    <div class="stats">
        <h3>📊 System Performance</h3>
        <div class="metric">
            <div class="number">{stats['runs']}</div>
            <div class="label">Agent Runs</div>
        </div>
        <div class="metric">
            <div class="number">{stats['total_articles_found']}</div>
            <div class="label">Critical Articles Found</div>
        </div>
        <div class="metric">
            <div class="number">{stats['total_articles_found'] / max(stats['runs'], 1):.1f}</div>
            <div class="label">Avg Articles Per Run</div>
        </div>
    </div>
    
    <div class="stats">
        <h3>🔍 Operational Status</h3>
        {self.get_status_message(stats)}
    </div>
    
    <div class="stats">
        <h3>⏰ Run Schedule</h3>
        <p>Agent ran {stats['runs']} times throughout the day</p>
        <p>Monitoring 6 RSS sources for Borouge/ADNOC operational impact</p>
        <p>Time window: 6 hours of coverage per run</p>
    </div>
    
    <div class="footer">
        <p><em>This daily summary is generated by the AI Logistics Monitor for Borouge/ADNOC operations.</em></p>
        <p><em>System runs automatically every hour and sends alerts for critical logistics incidents.</em></p>
    </div>
</body>
</html>"""
        
        # Send email
        msg = MIMEMultipart()
        msg['From'] = sender
        msg['To'] = recipient
        msg['Subject'] = f'📊 Daily Logistics Summary - {yesterday_str}'
        
        msg.attach(MIMEText(html_content, 'html'))
        
        try:
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)
            server.quit()
            
            print(f"📊 Daily summary sent for {yesterday_str}")
            return True
        except Exception as e:
            print(f"❌ Daily summary failed: {e}")
            return False
    
    def get_status_message(self, stats):
        if stats['total_articles_found'] == 0:
            return "✅ <strong>Excellent:</strong> No critical logistics incidents detected. Operations running smoothly."
        elif stats['total_articles_found'] <= 3:
            return "🟡 <strong>Normal:</strong> Low level of logistics activity detected. Routine monitoring."
        elif stats['total_articles_found'] <= 10:
            return "🟠 <strong>Active:</strong> Moderate logistics activity detected. Stay alert."
        else:
            return "🔴 <strong>High Activity:</strong> Significant logistics developments detected. Review individual alerts."

# Global tracker instance
summary_tracker = DailySummaryTracker()
