import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import pytz
import os

def send_email(articles):
    """Send email alert with logistics news articles"""
    
    # Get email configuration
    sender = os.environ.get('LOGISTICS_EMAIL_USER', 'sc.sentinelnews@gmail.com')
    password = os.environ.get('LOGISTICS_EMAIL_PASSWORD', '')
    recipient = os.environ.get('LOGISTICS_EMAIL_RECIPIENT', sender)
    
    print(f"🔧 Debug - Sender: {sender}")
    print(f"🔧 Debug - Recipient: {recipient}")
    print(f"🔧 Debug - Password length: {len(password) if password else 0}")
    print(f"🔧 Debug - Articles count: {len(articles)}")
    
    # Create HTML email content
    current_time = datetime.now(pytz.UTC).strftime('%Y-%m-%d %H:%M:%S')
    
    html_content = f"""<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background-color: #f2f2f2; }}
        .alert {{ color: #d32f2f; font-weight: bold; }}
    </style>
</head>
<body>
    <h2>🚢 Logistics Intelligence Alert</h2>
    <p><strong>Time:</strong> {current_time} UTC</p>
    <table>
        <tr>
            <th>S.No</th>
            <th>News Category</th>
            <th>News Content</th>
            <th>Source</th>
        </tr>"""
    
    for i, article in enumerate(articles, 1):
        html_content += f"""
        <tr>
            <td>{i}</td>
            <td>{article.get('category', 'General')}</td>
            <td>{article.get('title', 'No title')}</td>
            <td>{article.get('source', 'Unknown')}</td>
        </tr>"""
    
    html_content += """
    </table>
    <hr>
    <p><em>This alert was generated by AI Logistics Monitor for Borouge/ADNOC operations.</em></p>
</body>
</html>"""
    
    # Create email message
    msg = MIMEMultipart()
    msg['From'] = sender
    msg['To'] = recipient
    msg['Subject'] = f'🚢 Logistics Alert - {len(articles)} Critical Updates Found'
    
    msg.attach(MIMEText(html_content, 'html'))
    
    print("🔧 Debug - Attempting to send email...")
    
    # Send email
    try:
        server = smtplib.SMTP('smtp.gmail.com', 587)
        print("🔧 Debug - SMTP server connected")
        server.starttls()
        print("🔧 Debug - TLS started")
        server.login(sender, password)
        print("🔧 Debug - Login successful")
        server.send_message(msg)
        print("🔧 Debug - Message sent")
        server.quit()
        print(f"📧 Email sent successfully to {recipient}")
        return True
    except Exception as e:
        print(f"❌ Email failed: {e}")
        print(f"🔧 Debug - Error type: {type(e)}")
        return False
