import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
import json

class EmailNotifier:
    def __init__(self):
        self.smtp_server = 'smtp.gmail.com'
        self.smtp_port = 587
        self.sender = os.getenv('LOGISTICS_EMAIL_USER', '')
        self.recipient = os.getenv('LOGISTICS_EMAIL_RECIPIENT', '')
        self.password = os.getenv('LOGISTICS_EMAIL_PASSWORD', '')
    
    def create_html_table(self, articles):
        """Create HTML table for email content"""
        html_table = """
        <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%; font-family: Arial, sans-serif;">
            <thead style="background-color: #f2f2f2; font-weight: bold;">
                <tr>
                    <th style="text-align: left; width: 5%;">S.no</th>
                    <th style="text-align: left; width: 20%;">News Category</th>
                    <th style="text-align: left; width: 55%;">News Content</th>
                    <th style="text-align: left; width: 20%;">Source</th>
                </tr>
            </thead>
            <tbody>
        """
        
        for i, article in enumerate(articles[:10], 1):  # Limit to 10 articles
            html_table += f"""
                <tr>
                    <td style="vertical-align: top;">{i}</td>
                    <td style="vertical-align: top;">{article['category']}</td>
                    <td style="vertical-align: top;">
                        <strong>{article['title']}</strong><br>
                        <small>{article['summary']}</small><br>
                        <span class="article-info">Source: {article['source']}</span>
                    </td>
                    <td style="vertical-align: top;">
                        <span class="source-verified">{article['source'].title()}</span>
                    </td>
                </tr>
            """
        
        html_table += """
            </tbody>
        </table>
        """
        
        return html_table
    
    def send_alert(self, articles, subject=None):
        """Send email alert with articles"""
        try:
            if not articles:
                print("❌ No articles to send")
                return False
            
            if not self.sender or not self.recipient or not self.password:
                print("❌ Missing email credentials")
                return False
            
            # Create email
            msg = MIMEMultipart()
            
            # Use custom subject or default
            if subject:
                email_subject = subject
            else:
                email_subject = f"🚢 Global Logistics Alert - {datetime.now().strftime('%Y-%m-%d')}"
            
            msg['Subject'] = email_subject
            msg['From'] = self.sender
            msg['To'] = self.recipient
            
            # Create HTML content
            html_content = f"""
            <html>
            <body style="font-family: Arial, sans-serif; margin: 20px;">
                <h2 style="color: #2c3e50;">🚢 Global Logistics Alert</h2>
                <p style="color: #7f8c8d;">Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
                {self.create_html_table(articles)}
                <hr style="border: none; border-top: 1px solid #ecf0f1; margin: 20px 0;">
                <p style="color: #95a5a6; font-size: 12px;">
                    This is an automated logistics monitoring system for educational purposes only.
                    <br>Generated by Global Logistics Monitor V2
                </p>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(html_content, 'html'))
            
            # Send email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.sender, self.password)
            text = msg.as_string()
            server.sendmail(self.sender, self.recipient, text)
            server.quit()
            
            return True
            
        except Exception as e:
            print(f"❌ Error sending email: {e}")
            return False

# Global instance for backward compatibility
email_notifier = EmailNotifier()
